#!/usr/bin/env bash

# Simple Script for launching Brave's Profiles

# If Brave
DIR_PROFILES=$HOME/.config/BraveSoftware/Brave-Browser/

# Get profile names from json file 'Preferences'
profile_directories=$(fd -g Preferences -t file "$DIR_PROFILES" -E "Guest Profile" -E "System Profile" -E "/Preferences" -x jq '.profile.name')

# Pipe profile names, use sed to remove double quotes and show them in dmenu.
chosen_profile=$(echo -e "$profile_directories" | cut -d'/' -f7 | sed 's/"//g' | dmenu -i -h 24 -p "Profile: ")

# If nothing is selected, exit the script.
[[ $chosen_profile ]] || exit

# Target profile to search for.
target_profile="\"name\":\"$chosen_profile\""

# Search for "name":"profile-name" in Preferences file and get profile folder
PROFILE_FOLDER=$(rg -lF "$target_profile" "$DIR_PROFILES" -g '!Local State')

# Cut profile path and get the folder where the Preferences file is located
final_profile=$(echo "$PROFILE_FOLDER" | cut -d'/' -f7)

# If nothing is selected, exit the script.
[[ $final_profile ]] || exit

# execute Brave
brave --profile-directory="$final_profile" >/dev/null 2>&1 &
